---
discord:
  url: "https://discord.gg/tuservidor"
  cooldown: 5

npc:
  name: "§9§lDISCORD"
  name-line-2: "§7Toca para entrar"
  scale: 1.0
  look-at-players: true
  look-range: 12.0

messages:
  prefix: "§8[§9Discord§8] §r"
  interact: "§bEntra a nuestro Discord:"
  spawned: "§aNPC de Discord creado."
  removed: "§aNPC eliminado."
  removed-all: "§aEliminados §e{count} §aNPCs."
  none-near: "§cNo hay ningun NPC cerca."
  players-only: "§cSolo en el juego."
  cooldown: "§7Espera un momento."
...
